const fs = require('fs');

let storeHtml = fs.readFileSync('public/apps/store-dragdrop/index.html', 'utf8');

// Remove OLD incomplete light theme CSS to replace with updated one
storeHtml = storeHtml.replace(/\/\* ===== COMPLETE LIGHT THEME =====[\s\S]*?\/\* Step bar \*\/\n    html\[data-theme="light"\] #moveStepBar \{\n      background: rgba\(240,244,248,0\.9\) !important;\n    \}\n/m, '');

const completeLightCSS = `
    /* ===== COMPLETE LIGHT THEME ===== */
    html[data-theme="light"] {
      --bg: #f8fafc;
      --card: #ffffff;
      --card2: #f1f5f9;
      --border: rgba(15,23,42,0.12);
      --blue: #2563eb;
      --green: #16a34a;
      --amber: #d97706;
      --red: #dc2626;
      --text: #0f172a;
      --muted: #64748b;
      --teal: #0d9488;
    }

    /* Base */
    html[data-theme="light"] body {
      background: #f8fafc !important;
      color: #0f172a !important;
    }

    /* Override inline styles generated by app.js for dark mode */
    html[data-theme="light"] *[style*="color:#e2e8f0"],
    html[data-theme="light"] *[style*="color: #e2e8f0"] { color: #0f172a !important; font-weight: 700 !important; }
    
    html[data-theme="light"] *[style*="color:#fbbf24"],
    html[data-theme="light"] *[style*="color: #fbbf24"] { color: #d97706 !important; }
    
    html[data-theme="light"] *[style*="color:#4ade80"],
    html[data-theme="light"] *[style*="color: #4ade80"] { color: #16a34a !important; }
    
    html[data-theme="light"] *[style*="color:#f87171"],
    html[data-theme="light"] *[style*="color: #f87171"] { color: #dc2626 !important; }
    
    html[data-theme="light"] *[style*="color:#60a5fa"],
    html[data-theme="light"] *[style*="color: #60a5fa"] { color: #2563eb !important; }
    
    html[data-theme="light"] *[style*="color:#94a3b8"],
    html[data-theme="light"] *[style*="color: #94a3b8"] { color: #64748b !important; }
    
    html[data-theme="light"] *[style*="color:#64748b"],
    html[data-theme="light"] *[style*="color: #64748b"] { color: #475569 !important; }

    /* Override ALL hardcoded dark backgrounds used in lists, modals, and badges */
    html[data-theme="light"] *[style*="background:rgba(15,23,42,0.4)"],
    html[data-theme="light"] *[style*="background: rgba(15,23,42,0.4)"],
    html[data-theme="light"] *[style*="background:rgba(15,23,42,0.5)"],
    html[data-theme="light"] *[style*="background: rgba(15,23,42,0.5)"],
    html[data-theme="light"] *[style*="background:rgba(30,41,59,0.5)"],
    html[data-theme="light"] *[style*="background: rgba(30,41,59,0.5)"],
    html[data-theme="light"] *[style*="background:rgba(30,41,59,0.6)"],
    html[data-theme="light"] *[style*="background: rgba(30,41,59,0.6)"],
    html[data-theme="light"] *[style*="background:rgba(15,23,42,0.7)"],
    html[data-theme="light"] *[style*="background: rgba(15,23,42,0.7)"] {
      background: #f1f5f9 !important;
      border: 1px solid rgba(15,23,42,0.1) !important;
      color: #0f172a !important;
      box-shadow: inset 0 1px 2px rgba(255,255,255,0.8);
    }

    html[data-theme="light"] *[style*="background:rgba(15,23,42,0.6)"],
    html[data-theme="light"] *[style*="background: rgba(15,23,42,0.6)"] {
      background: #e2e8f0 !important;
      color: #334155 !important;
      border: 1px solid rgba(15,23,42,0.08) !important;
    }

    html[data-theme="light"] *[style*="background:rgba(255,255,255,0.03)"],
    html[data-theme="light"] *[style*="background: rgba(255,255,255,0.03)"] {
      background: #ffffff !important;
      border: 1px solid rgba(15,23,42,0.1) !important;
      box-shadow: 0 1px 3px rgba(15,23,42,0.04) !important;
    }

    html[data-theme="light"] *[style*="border-bottom:1px solid rgba(51,65,85,0.3)"] {
      border-bottom-color: rgba(15,23,42,0.08) !important;
    }

    /* Main content area */
    html[data-theme="light"] .main-content { background: #f8fafc !important; }

    /* Store Manager inner Sidebar - Make it LIGHT */
    html[data-theme="light"] .sidebar {
      background: #ffffff !important;
      border-right: 1px solid rgba(15,23,42,0.08) !important;
    }
    html[data-theme="light"] .sidebar-btn {
      color: #475569 !important;
    }
    html[data-theme="light"] .sidebar-btn:hover {
      background: #f1f5f9 !important;
    }
    html[data-theme="light"] .sidebar-btn.active {
      background: #eff6ff !important;
      color: #2563eb !important;
    }
    
    /* Sidebar bottom buttons */
    html[data-theme="light"] .sidebar-action-btn {
      background: #f1f5f9 !important;
      color: #334155 !important;
      border: 1px solid rgba(15,23,42,0.1) !important;
    }
    html[data-theme="light"] .sidebar-action-btn:hover {
      background: #e2e8f0 !important;
    }

    /* Top bar / Page header */
    html[data-theme="light"] .top-bar,
    html[data-theme="light"] .page-header {
      background: rgba(240,244,248,0.96) !important;
      border-bottom: 1px solid rgba(15,23,42,0.10) !important;
    }
    html[data-theme="light"] .page-header-title,
    html[data-theme="light"] .page-header-sub { color: #0f172a !important; }

    /* Location cards */
    html[data-theme="light"] .glass-card,
    html[data-theme="light"] .loc-card {
      background: #ffffff !important;
      border: 1px solid rgba(15,23,42,0.10) !important;
      box-shadow: 0 1px 4px rgba(15,23,42,0.05) !important;
    }
    html[data-theme="light"] .loc-card:active { background: #f8fafc !important; }
    html[data-theme="light"] .loc-card .loc-name { color: #0f172a !important; font-weight: 700; }
    html[data-theme="light"] .loc-card .loc-count { color: #475569 !important; font-weight: 600; }

    /* Bottom nav */
    html[data-theme="light"] .navbar {
      background: #ffffff !important;
      border-top: 1px solid rgba(15,23,42,0.10) !important;
    }
    html[data-theme="light"] .nav-btn { color: #64748b !important; }
    html[data-theme="light"] .nav-btn.active { color: #2563eb !important; font-weight: 600; }

    /* Inventory rows - force text color */
    html[data-theme="light"] div[data-item-name] > div:nth-child(2) > div:first-child { color: #0f172a !important; font-weight: 700 !important; }
    html[data-theme="light"] div[data-item-name] > div:nth-child(2) > div:last-child { color: #475569 !important; font-weight: 500 !important; }
    html[data-theme="light"] div[data-item-name]:hover { background: rgba(37,99,235,0.03) !important; }

    /* Adjust button ⚖️ */
    html[data-theme="light"] .adj-btn {
      background: #fef3c7 !important;
      border-color: #fcd34d !important;
      color: #d97706 !important;
    }
    html[data-theme="light"] .adj-btn:hover { background: #fde68a !important; }

    /* Icons (Chevron, Category Order) */
    html[data-theme="light"] .group-chevron, 
    html[data-theme="light"] .cat-order-btn {
      background: #e2e8f0 !important;
      color: #334155 !important;
      border: 1px solid rgba(15,23,42,0.1) !important;
    }
    html[data-theme="light"] .group-chevron:hover, 
    html[data-theme="light"] .cat-order-btn:hover { background: #cbd5e1 !important; }

    /* Group header */
    html[data-theme="light"] .group-header { background: #e2e8f0 !important; border-bottom: 1px solid rgba(15,23,42,0.06) !important; }
    html[data-theme="light"] .group-header .group-title { color: #1e293b !important; font-weight: 700; }

    /* Filter pills */
    html[data-theme="light"] .filter-pill {
      background: #ffffff !important;
      border-color: rgba(15,23,42,0.12) !important;
      color: #334155 !important;
      font-weight: 600;
    }
    html[data-theme="light"] .filter-pill.active {
      background: #2563eb !important;
      color: #ffffff !important;
      border-color: #2563eb !important;
    }

    /* History / Pending items */
    html[data-theme="light"] .timeline-item {
      background: transparent !important;
      border: none !important;
      padding: 0 !important;
    }
    html[data-theme="light"] .timeline-dot {
      background: #f8fafc !important; /* Ensure it stays light */
      /* dotColor opacity override */
      box-shadow: inset 0 0 0 20px rgba(255,255,255,0.7);
    }
    
    html[data-theme="light"] .glass-card > div[style*="margin-bottom:10px"] span { font-weight: 800 !important; }

    /* Form inputs */
    html[data-theme="light"] .form-input,
    html[data-theme="light"] .form-select {
      background: #ffffff !important;
      color: #0f172a !important;
      border: 1px solid rgba(15,23,42,0.15) !important;
      font-weight: 500;
    }
    html[data-theme="light"] .form-input:focus { border-color: #2563eb !important; box-shadow: 0 0 0 2px rgba(37,99,235,0.1) !important; }

    /* Modal */
    html[data-theme="light"] .modal-sheet { background: #ffffff !important; border: 1px solid rgba(15,23,42,0.10) !important; }
    html[data-theme="light"] .modal-title { color: #0f172a !important; font-weight: 700; }

    /* Section cards inside modals */
    html[data-theme="light"] .section-card { background: #f8fafc !important; border: 1px solid rgba(15,23,42,0.08) !important; }
    html[data-theme="light"] .section-title { color: #334155 !important; font-weight: 700; }

    /* Sort banner */
    html[data-theme="light"] #sortModeBanner { background: #eff6ff !important; border-color: #bfdbfe !important; color: #1e3a8a !important; }

    /* Skeleton shimmer */
    html[data-theme="light"] .skeleton {
      background: linear-gradient(90deg, #f1f5f9 25%, #ffffff 50%, #f1f5f9 75%) !important;
      background-size: 200% auto !important;
    }

    /* Adj info box */
    html[data-theme="light"] #adjustItemInfo { background: #f1f5f9 !important; border: 1px solid rgba(15,23,42,0.06) !important; }

    /* Undo info */
    html[data-theme="light"] #undoInfo { background: #fef2f2 !important; border-color: #fca5a5 !important; color: #991b1b !important; }

    /* Sort handle */
    html[data-theme="light"] .sort-handle { color: #94a3b8 !important; }

    /* Loc manage row toggle */
    html[data-theme="light"] .loc-manage-row,
    html[data-theme="light"] .cat-manage-row {
      background: #f8fafc !important;
      border: 1px solid rgba(15,23,42,0.08) !important;
      color: #0f172a !important;
    }

    /* Step bar */
    html[data-theme="light"] #moveStepBar { background: #f0f4f8 !important; border-bottom: 1px solid rgba(15,23,42,0.08) !important; }
`;

// Find where to inject - after the ::-webkit-scrollbar rule
storeHtml = storeHtml.replace(
  '::-webkit-scrollbar-thumb { background: var(--border); border-radius: 2px; }',
  '::-webkit-scrollbar-thumb { background: var(--border); border-radius: 2px; }' + completeLightCSS
);

fs.writeFileSync('public/apps/store-dragdrop/index.html', storeHtml);
console.log('Store Manager: Complete Light Theme injected');
